from azureiotedge/azureiotedge-module-base:1.0.3-linux-arm64v8

RUN apt-get update 


# Add the application
ADD app ../FarmBeatsLabModule/app

# Set the working directory
WORKDIR /app

ENTRYPOINT [ "python3", "-u", "./main.py" ]
