#FROM azureiotedge/azureiotedge-module-base:1.0.3-linux-arm64v8
#FROM azureiotedge/azureiotedge-module-base:1.0.0-preview015-linux-arm64v8
FROM  arm64v8/ubuntu:16.04

RUN apt-get update

RUN  apt-get install -y python3-pip python3-venv
RUN  pip3 install -U pip

# Add the application
COPY FarmBeatsLabModule/app app

# Set the working directory
WORKDIR /app

RUN pip3 install --trusted-host pypi.python.org -r FarmBeatsLabModule/requirements.txt


ENTRYPOINT [ "python3", "-u", "./main.py" ]
